services:
  backend:
    build:
      context: ./backend
    container_name: personal-finance-dashboard-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:///data/finance.db
      SECRET_KEY: supersecretdevkey
      MOCK_BANK_URL: http://104.248.41.128:8000
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
    container_name: personal-finance-dashboard-frontend
    ports:
      - "3000:3000"
